import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/layout/Header'
import { Montserrat as FontSans } from "next/font/google"
import { cn } from "../lib/utils"
import { Toaster } from '@/components/ui/sonner'
import AuthProvider from '@/components/AuthProvider'
export const fontSans = FontSans({
  subsets: ["vietnamese"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: 'Mô hình cao cấp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
          
      <body 
       className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}
      >
        <AuthProvider>
      <Header/>
        
        {children}
        <Toaster />
        </AuthProvider>
        </body>
    </html>
  )
}
